### ISSUE TITLE
SyntaxError: Unexpected token h in JSON at position 0

### ISSUE THREAD

**Issue by GiTuur** [robertklep/nefit-easy-http-server#19]
Hi, I just installed the nefit-easy-server but getting error when trying to get status:
# curl http://127.0.0.1:3000/api/status
SyntaxError: Unexpected token h in JSON at position 0
    at Object.parse (native)
    at pending.(anonymous function).send.then.e (/volume1/@appstore/Node.js_v6/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:236:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Any idea what I'm doing wrong?

**Comment by robertklep** [comment]
This is typically caused by invalid credentials (serial, password, access code).

Be aware that there's a (long-standing) bug in the code that prevents the use of certain characters in the password. At least one known character that will cause problems in the password is `!`, but there might be others.

**Comment by GiTuur** [comment]
no character issue but password lenght. thx

**Comment by robertklep** [comment]
@GiTuur glad it's solved!

Any idea what the maximum length is? If there's a maximum, I think the Nefit app might just truncate passwords that are longer, which is something I could implement too (or at least show the user a warning).

**Comment by GiTuur** [comment]
Hi Robert, the maximun lenght is 10 characters

**Comment by robertklep** [comment]
Good to know, thanks!
