### ISSUE TITLE
Receive xmpp messages from backend

### ISSUE THREAD

**Issue by adhyh** [robertklep/nefit-easy-http-server#49]
When i change anything on my nefit easy iOS app it instantly changes on my wall thermostat and vice versa. I assumed an xmpp message is sent to the thermostat/iOS device to inform about the change. 
- Is my assumption correct?
- Are these messages also sent to the nefit-easy-core client?
- With debug=* I didn't see anything. Is there a way for the nefit-easy-core to sync  a change other than to poll every x seconds?

**Comment by robertklep** [comment]
I never really looked at how that mechanism works, but looking at the code of a (very) old Android app, it looks like XMPP is used for the regular request-response flow, and a separate UDP listener is used to receive notifications from the thermostat.

The latter would be easy to test by using a mobile network instead of your local WiFi, and then updating the status on your wall thermostat. If my assumption is correct, it should take a while before the update is visible in the iOS app (I don't have an Easy anymore so cannot test myself).

In any case, `nefit-easy-core` can only be used in a polling setup 🙁

**Comment by adhyh** [comment]
Thanks for the pointers Robert, I'm going to take a look..
